const floors=['Ground Floor','First Floor','Second Floor','Third Floor'];
const seed={A:['001','002','003','004','101','102','103','104','105','106','107','108','109','110','111','201','202','203','204','205','206','207','208','209','210','211','301','302','303','304','305','306','307','308','309','310','311'],B:['001','002','003','004','101','102','103','104','105','106','107','108','109','110','111','201','202','203','204','205','206','207','208','209','210','211','301','302','303','304','305','306','307','308','309','310','311'],C:['001','002','003','004','101','102','103','104','105','106','107','108','109','110','111','201','202','203','204','205','206','207','208','209','210','211','301','302','303','304','305','306','307','308','309','310','311']};
const block=new URLSearchParams(location.search).get('block')||'A';
const blockName=block==='library'?'Library / Common Zone':`Block ${block}`;
const API_BASE_URL=window.CAMPUS_API_BASE_URL;
async function apiFetch(path){const response=await fetch(`${API_BASE_URL}${path}`,{headers:{Accept:'application/json'}});let data;try{data=await response.json()}catch{throw new Error(`Backend returned invalid JSON (${response.status})`)}if(!response.ok)throw new Error(data.detail||`Backend request failed (${response.status})`);return data}
let saved={};try{saved=JSON.parse(sessionStorage.getItem('campus-pulse-state-v2'))||{} }catch{}
let rooms=(saved.rooms||seed[block].map((id,i)=>({id:`${block}${id}`,floor:+id<100?floors[0]:floors[Math.floor(+id/100)],occupied:i%3!==0,energyToday:1}))).filter(r=>r.block===block||r.id?.startsWith(block));
function applyApiRooms(data){rooms=data.rooms.filter(room=>room.block===block).map(room=>{const appliances=room.appliances||{};return{id:room.id,block:room.block,floor:room.floor,occupied:Boolean(room.occupied),energyToday:Number(room.energy_kwh||0),warning:Boolean(room.warning),light:Boolean(appliances.light?.actual),fan:Boolean(appliances.fan?.actual),ac:Boolean(appliances.ac?.actual)}});render();}
const floorRooms=f=>rooms.filter(r=>r.floor===f);const load=rs=>rs.reduce((sum,r)=>sum+(r.light?.08:0)+(r.fan?.12:0)+(r.ac?1.2:0),0);const image=f=>block==='library'?'assets/campus-layout.jpg':`assets/${f.toLowerCase().replace(' floor','-floor')}.png`;
function render(floor='Ground Floor'){let rs=floorRooms(floor),occupied=rs.filter(r=>r.occupied).length,percent=Math.round(occupied/Math.max(rs.length,1)*100),kw=load(rs),eff=kw>4?'High Usage':kw>2?'Moderate':'Efficient';document.querySelector('#blockDetailApp').innerHTML=`<div class="shell"><aside class="sidebar"><a class="brand" href="dashboard.html">⚡ Smart Campus</a><nav><a href="dashboard.html">Dashboard</a><a class="active" href="campus-map.html">Campus Map</a><a href="rooms.html">Rooms</a><a href="energy.html">Energy Analytics</a><a href="alerts.html">Alerts</a><a href="ai-insights.html">AI Insights</a><a href="hardware.html">Hardware Readiness</a></nav><nav class="bottom"><a href="settings.html">⚙ Settings</a><a href="index.html">↪ Logout</a></nav></aside><main><header><div><p class="eyebrow">CAMPUS 25 · LIVE</p><h1>Campus 25</h1><p class="muted">Smart Occupancy & Energy Heat Map</p></div><div class="profile"><span>${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span><b class="avatar">A</b> Admin</div></header><section class="content block-detail-content"><a class="back" href="campus-map.html">← Back to Campus Map</a><div class="block-layout"><section class="card block-main"><div class="block-heading"><div><span class="eyebrow">● LIVE BLOCK DATA</span><h2>Block ${block}</h2><p class="muted">Live simulated occupancy and energy efficiency overview.</p></div><span class="badge ${eff.toLowerCase().replace(' ','-')}">${eff}</span></div><div class="block-kpis"><article><small>Current occupancy</small><strong>${percent}%</strong></article><article><small>Live energy</small><strong>${kw.toFixed(2)} kW</strong></article><article><small>Efficiency score</small><strong>${Math.max(0,100-Math.round(kw*2))}%</strong></article><article><small>Active alerts</small><strong>${rs.filter(r=>r.warning).length}</strong></article></div><div class="efficiency-callout"><b>${eff}</b><span>Automation status: ACTIVE</span></div><div class="floor-heading"><h3>Floor Plan</h3><div class="floor-tabs">${floors.map(x=>`<button class="detail-floor ${x===floor?'selected':''}" data-floor="${x}">${x}</button>`).join('')}</div></div><div class="detail-floor-plan"><img src="${image(floor)}" alt="Block ${block} ${floor} floor plan"></div><div class="room-status"><span class="status-dot ${eff.toLowerCase().replace(' ','-')}"></span><b>${eff}</b>${rs.slice(0,10).map(r=>`<a href="rooms.html?room=${r.id}">${r.id}</a>`).join('')}</div></section><aside class="card current-status"><h2>Current status</h2><p>Automation: <b>ACTIVE</b></p><p>Updated: <b>Just now</b></p><p>Mode: <b>Simulated monitoring</b></p></aside></div></section></main></div>`;document.querySelectorAll('.detail-floor').forEach(button=>button.onclick=()=>render(button.dataset.floor))}
render();
if(block==='library'){document.querySelector('.block-heading h2').textContent=blockName;document.querySelector('.detail-floor-plan img').alt=blockName;document.querySelector('.floor-heading h3').textContent='Campus Layout'}
apiFetch('/api/rooms').then(applyApiRooms).catch(error=>{const target=document.querySelector('#blockDetailApp');if(target)target.insertAdjacentHTML('afterbegin',`<p class="card muted">Backend unavailable: ${error.message}</p>`)})
