services:
  - type: web
    name: smart-campus
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SIMULATION_MODE
        value: "true"
      - key: FRONTEND_ORIGINS
        value: "https://smart-campus-nyql.vercel.app,https://smart-campus-red.vercel.app,http://127.0.0.1:5500,http://localhost:5500"
